transcript on
if {[file exists rtl_work]} {
	vdel -lib rtl_work -all
}
vlib rtl_work
vmap work rtl_work

vlib lab62soc
vmap lab62soc lab62soc
vlog -vlog01compat -work lab62soc +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/lab62soc.v}
vlog -vlog01compat -work lab62soc +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules/altera_reset_controller.v}
vlog -vlog01compat -work lab62soc +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules/altera_reset_synchronizer.v}
vlog -vlog01compat -work lab62soc +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules/lab62soc_mm_interconnect_0.v}
vlog -vlog01compat -work lab62soc +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules/lab62soc_mm_interconnect_0_avalon_st_adapter_005.v}
vlog -vlog01compat -work lab62soc +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules/lab62soc_mm_interconnect_0_avalon_st_adapter.v}
vlog -vlog01compat -work lab62soc +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules/altera_avalon_sc_fifo.v}
vlog -vlog01compat -work lab62soc +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules/lab62soc_usb_rst.v}
vlog -vlog01compat -work lab62soc +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules/lab62soc_usb_gpx.v}
vlog -vlog01compat -work lab62soc +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules/lab62soc_timer_0.v}
vlog -vlog01compat -work lab62soc +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules/lab62soc_sysid_qsys_0.v}
vlog -vlog01compat -work lab62soc +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules/lab62soc_spi_0.v}
vlog -vlog01compat -work lab62soc +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules/lab62soc_sdram_pll.v}
vlog -vlog01compat -work lab62soc +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules/lab62soc_sdram.v}
vlog -vlog01compat -work lab62soc +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules/lab62soc_onchip_memory2_0.v}
vlog -vlog01compat -work lab62soc +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules/lab62soc_nios2_gen2_0.v}
vlog -vlog01compat -work lab62soc +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules/lab62soc_nios2_gen2_0_cpu.v}
vlog -vlog01compat -work lab62soc +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules/lab62soc_nios2_gen2_0_cpu_debug_slave_sysclk.v}
vlog -vlog01compat -work lab62soc +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules/lab62soc_nios2_gen2_0_cpu_debug_slave_tck.v}
vlog -vlog01compat -work lab62soc +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules/lab62soc_nios2_gen2_0_cpu_debug_slave_wrapper.v}
vlog -vlog01compat -work lab62soc +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules/lab62soc_nios2_gen2_0_cpu_test_bench.v}
vlog -vlog01compat -work lab62soc +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules/lab62soc_leds_pio.v}
vlog -vlog01compat -work lab62soc +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules/lab62soc_keycode.v}
vlog -vlog01compat -work lab62soc +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules/lab62soc_key.v}
vlog -vlog01compat -work lab62soc +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules/lab62soc_jtag_uart_0.v}
vlog -vlog01compat -work lab62soc +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules/lab62soc_hex_digits_pio.v}
vlog -sv -work work +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/deflector {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/deflector/deflector_rom.sv}
vlog -sv -work work +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/deflector {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/deflector/deflector_palette.sv}
vlog -sv -work work +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/turret_45 {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/turret_45/turret_45_rom.sv}
vlog -sv -work work +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/turret_45 {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/turret_45/turret_45_palette.sv}
vlog -sv -work work +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/projectile_45 {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/projectile_45/projectile_45_rom.sv}
vlog -sv -work work +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/projectile_45 {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/projectile_45/projectile_45_palette.sv}
vlog -sv -work work +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/turret_180 {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/turret_180/turret_180_rom.sv}
vlog -sv -work work +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/turret_180 {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/turret_180/turret_180_palette.sv}
vlog -sv -work work +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/turret {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/turret/turret_rom.sv}
vlog -sv -work work +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/turret {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/turret/turret_palette.sv}
vlog -sv -work work +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/starrynight {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/starrynight/starrynight_rom.sv}
vlog -sv -work work +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/starrynight {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/starrynight/starrynight_palette.sv}
vlog -sv -work work +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/penguin_final {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/penguin_final/penguin_final_rom.sv}
vlog -sv -work work +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/penguin_final {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/penguin_final/penguin_final_palette.sv}
vlog -sv -work work +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/dogactualfinal {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/dogactualfinal/dogactualfinal_rom.sv}
vlog -sv -work work +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/dogactualfinal {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/dogactualfinal/dogactualfinal_palette.sv}
vlog -sv -work work +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2 {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/fullproject.sv}
vlog -sv -work work +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/projectile_180 {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/projectile_180/projectile_180_rom.sv}
vlog -sv -work work +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/projectile_180 {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/projectile_180/projectile_180_palette.sv}
vlog -sv -work work +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/rocketforfinal {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/rocketforfinal/rocketforfinal_rom.sv}
vlog -sv -work work +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/rocketforfinal {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/rocketforfinal/rocketforfinal_palette.sv}
vlog -sv -work work +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/rocketforfinal {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/rocketforfinal/rocketforfinal_example.sv}
vlog -sv -work work +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2 {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/VGA_controller.sv}
vlog -sv -work work +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2 {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62.sv}
vlog -sv -work work +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2 {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/HexDriver.sv}
vlog -sv -work lab62soc +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules/lab62soc_irq_mapper.sv}
vlog -sv -work lab62soc +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules/lab62soc_mm_interconnect_0_avalon_st_adapter_005_error_adapter_0.sv}
vlog -sv -work lab62soc +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules/lab62soc_mm_interconnect_0_avalon_st_adapter_error_adapter_0.sv}
vlog -vlog01compat -work lab62soc +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules/altera_avalon_st_handshake_clock_crosser.v}
vlog -vlog01compat -work lab62soc +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules/altera_avalon_st_clock_crosser.v}
vlog -vlog01compat -work lab62soc +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules/altera_std_synchronizer_nocut.v}
vlog -sv -work lab62soc +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules/altera_merlin_width_adapter.sv}
vlog -sv -work lab62soc +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules/altera_merlin_burst_uncompressor.sv}
vlog -sv -work lab62soc +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules/lab62soc_mm_interconnect_0_rsp_mux.sv}
vlog -sv -work lab62soc +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules/altera_merlin_arbitrator.sv}
vlog -sv -work lab62soc +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules/lab62soc_mm_interconnect_0_rsp_demux.sv}
vlog -sv -work lab62soc +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules/lab62soc_mm_interconnect_0_cmd_mux.sv}
vlog -sv -work lab62soc +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules/lab62soc_mm_interconnect_0_cmd_demux.sv}
vlog -sv -work lab62soc +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules/altera_merlin_burst_adapter.sv}
vlog -sv -work lab62soc +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules/altera_merlin_burst_adapter_uncmpr.sv}
vlog -sv -work lab62soc +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules/lab62soc_mm_interconnect_0_router_007.sv}
vlog -sv -work lab62soc +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules/lab62soc_mm_interconnect_0_router_002.sv}
vlog -sv -work lab62soc +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules/lab62soc_mm_interconnect_0_router.sv}
vlog -sv -work lab62soc +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules/altera_merlin_slave_agent.sv}
vlog -sv -work lab62soc +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules/altera_merlin_master_agent.sv}
vlog -sv -work lab62soc +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules/altera_merlin_slave_translator.sv}
vlog -sv -work lab62soc +incdir+C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules {C:/Users/harig/OneDrive/Documents/385/final/ECE385_FinalProject/other_files_6_2/lab62soc/synthesis/submodules/altera_merlin_master_translator.sv}

